name: "Terraform Format"

on:
  push:
    branches:
      - main

jobs:
  terraform-fmt:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: Format
        run: terraform fmt -recursive
